=== CANopenTerm/CANopenTerm/export/codb/codb.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for CANopen Profile data bases",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "index": {
        "type": "number"
      },
      "sub_indices": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "index": {
              "type": "number"
            },
            "desc": {
              "type": "string"
            },
            "kind": {
              "type": "number"
            },
            "data_type": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "number"
                },
                "attr": {
                  "type": "number"
                },
                "lower": {
                  "type": "number"
                },
                "upper": {
                  "type": "number"
                }
              },
              "required": [
                "type",
                "attr",
                "lower",
                "upper"
              ]
            },
            "access_type": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "number"
                },
                "attr": {
                  "type": "number"
                },
                "lower": {
                  "type": "number"
                },
                "upper": {
                  "type": "number"
                }
              },
              "required": [
                "type",
                "attr",
                "lower",
                "upper"
              ]
            },
            "low_limit": {
              "type": "object",
              "properties": {
                "value": {
                  "type": "number"
                },
                "attr": {
                  "type": "number"
                },
                "lower": {
                  "type": "number"
                },
                "upper": {
                  "type": "number"
                }
              },
              "required": [
                "value",
                "attr",
                "lower",
                "upper"
              ]
            },
            "high_limit": {
              "type": "object",
              "properties": {
                "value": {
                  "type": "number"
                },
                "attr": {
                  "type": "number"
                },
                "lower": {
                  "type": "number"
                },
                "upper": {
                  "type": "number"
                }
              },
              "required": [
                "value",
                "attr",
                "lower",
                "upper"
              ]
            },
            "default_value": {
              "type": "object",
              "properties": {
                "value": {
                  "type": "number"
                },
                "attr": {
                  "type": "number"
                },
                "lower": {
                  "type": "number"
                },
                "upper": {
                  "type": "number"
                }
              },
              "required": [
                "value",
                "attr",
                "lower",
                "upper"
              ]
            },
            "mappable": {
              "type": "object",
              "properties": {
                "value": {
                  "type": "boolean"
                },
                "attr": {
                  "type": "number"
                },
                "lower": {
                  "type": "number"
                },
                "upper": {
                  "type": "number"
                }
              },
              "required": [
                "value",
                "attr",
                "lower",
                "upper"
              ]
            },
            "unit": {
              "type": "string"
            }
          },
          "required": [
            "index",
            "desc",
            "kind",
            "data_type",
            "access_type",
            "low_limit",
            "high_limit",
            "default_value",
            "mappable"
          ]
        }
      },
      "code": {
        "type": "object",
        "properties": {
          "type": {
            "type": "number"
          },
          "attr": {
            "type": "number"
          },
          "lower": {
            "type": "number"
          },
          "upper": {
            "type": "number"
          }
        },
        "required": [
          "type",
          "attr",
          "lower",
          "upper"
        ]
      },
      "min_elements": {
        "type": "object",
        "properties": {
          "value": {
            "type": "number"
          },
          "attr": {
            "type": "number"
          },
          "lower": {
            "type": "number"
          },
          "upper": {
            "type": "number"
          }
        },
        "required": [
          "value",
          "attr",
          "lower",
          "upper"
        ]
      },
      "max_elements": {
        "type": "object",
        "properties": {
          "value": {
            "type": "number"
          },
          "attr": {
            "type": "number"
          },
          "lower": {
            "type": "number"
          },
          "upper": {
            "type": "number"
          }
        },
        "required": [
          "value",
          "attr",
          "lower",
          "upper"
        ]
      },
      "desc": {
        "type": "string"
      },
      "kind": {
        "type": "number"
      }
    },
    "required": [
      "id",
      "index",
      "sub_indices",
      "code",
      "min_elements",
      "max_elements",
      "desc",
      "kind"
    ]
  }
}

=== CANopenTerm/CANopenTerm/export/codb/ds419.json
[{"id":"1000","index":4096,"sub_indices":[{"index":0,"desc":"Device Type","kind":1,"data_type":{"type":9,"attr":0,"lower":0,"upper":0},"access_type":{"type":2,"attr":0,"lower":0,"upper":0},"low_limit":{"value":0,"attr":0,"lower":0,"upper":0},"high_limit":{"value":0,"attr":0,"lower":0,"upper":0},"default_value":{"value":419,"attr":0,"lower":0,"upper":0},"mappable":{"value":false,"attr":0,"lower":0,"upper":0}}],"code":{"type":3,"attr":1,"lower":419,"upper":0},"min_elements":{"value":0,"attr":0,"lower":0,"upper":0},"max_elements":{"value":0,"attr":0,"lower":0,"upper":0},"desc":"Device Type","kind":1},{"id":"6000","index":24576,"sub_indices":[{"index":0,"desc":"Battery_status","kind":1,"data_type":{"type":3,"attr":0,"lower":0,"upper":0},"access_type":{"type":4,"attr":0,"lower":0,"upper":0},"low_limit":{"value":0,"attr":0,"lower":0,"upper":0},"high_limit":{"value":0,"attr":0,"lower":0,"upper":0},"default_value":{"value":0,"attr":0,"lower":0,"upper":0},"mappable":{"value":true,"attr":0,"lower":0,"upper":0}}],"code":{"type":3,"attr":2,"lower":0,"upper":0},"min_elements":{"value":0,"attr":0,"lower":0,"upper":0},"max_elements":{"value":0,"attr":0,"lower":0,"upper":0},"desc":"Battery_status","kind":1},{"id":"6001","index":24577,"sub_indices":[{"index":0,"desc":"Charger_status","kind":1,"data_type":{"type":3,"attr":0,"lower":0,"upper":0},"access_type":{"type":2,"attr":0,"lower":0,"upper":0},"low_limit":{"value":0,"attr":0,"lower":0,"upper":0},"high_limit":{"value":0,"attr":0,"lower":0,"upper":0},"default_value":{"value":0,"attr":0,"lower":0,"upper":0},"mappable":{"value":true,"attr":0,"lower":0,"upper":0}}],"code":{"type":3,"attr":2,"lower":0,"upper":0},"min_elements":{"value":0,"attr":0,"lower":0,"upper":0},"max_elements":{"value":0,"attr":0,"lower":0,"upper":0},"desc":"Charger_status","kind":1},{"id":"6010","index":24592,"sub_indices":[{"index":0,"desc":"Temperature","kind":1,"data_type":{"type":4,"attr":0,"lower":0,"upper":0},"access_type":{"type":4,"attr":0,"lower":0,"upper":0},"low_limit":{"value":0,"attr":0,"lower":0,"upper":0},"high_limit":{"value":0,"attr":0,"lower":0,"upper":0},"default_value":{"value":0,"attr":0,"lower":0,"upper":0},"mappable":{"value":true,"attr":0,"lower":0,"upper":0}}],"code":{"type":3,"attr":2,"lower":0,"upper":0},"min_elements":{"value":0,"attr":0,"lower":0,"upper":0},"max_elements":{"value":0,"attr":0,"lower":0,"upper":0},"desc":"Temperature","kind":1},{"id":"6052","index":24658,"sub_indices":[{"index":0,"desc":"Ah_returned_during_last_charge","kind":0,"data_type":{"type":5,"attr":0,"lower":0,"upper":0},"access_type":{"type":2,"attr":0,"lower":0,"upper":0},"low_limit":{"value":0,"attr":0,"lower":0,"upper":0},"high_limit":{"value":0,"attr":0,"lower":0,"upper":0},"default_value":{"value":0,"attr":0,"lower":0,"upper":0},"mappable":{"value":true,"attr":0,"lower":0,"upper":0}}],"code":{"type":3,"attr":2,"lower":0,"upper":0},"min_elements":{"value":0,"attr":0,"lower":0,"upper":0},"max_elements":{"value":0,"attr":0,"lower":0,"upper":0},"desc":"Ah_returned_during_last_charge","kind":0},{"id":"6060","index":24672,"sub_indices":[{"index":0,"desc":"Battery_voltage","kind":0,"data_type":{"type":9,"attr":0,"lower":0,"upper":0},"access_type":{"type":4,"attr":0,"lower":0,"upper":0},"low_limit":{"value":0,"attr":0,"lower":0,"upper":0},"high_limit":{"value":0,"attr":0,"lower":0,"upper":0},"default_value":{"value":0,"attr":0,"lower":0,"upper":0},"mappable":{"value":true,"attr":0,"lower":0,"upper":0}}],"code":{"type":3,"attr":2,"lower":0,"upper":0},"min_elements":{"value":0,"attr":0,"lower":0,"upper":0},"max_elements":{"value":0,"attr":0,"lower":0,"upper":0},"desc":"Battery_voltage","kind":0},{"id":"6070","index":24688,"sub_indices":[{"index":0,"desc":"Charge_current_requested","kind":0,"data_type":{"type":5,"attr":0,"lower":0,"upper":0},"access_type":{"type":4,"attr":0,"lower":0,"upper":0},"low_limit":{"value":0,"attr":0,"lower":0,"upper":0},"high_limit":{"value":0,"attr":0,"lower":0,"upper":0},"default_value":{"value":0,"attr":0,"lower":0,"upper":0},"mappable":{"value":true,"attr":0,"lower":0,"upper":0}}],"code":{"type":3,"attr":2,"lower":0,"upper":0},"min_elements":{"value":0,"attr":0,"lower":0,"upper":0},"max_elements":{"value":0,"attr":0,"lower":0,"upper":0},"desc":"Charge_current_requested","kind":0},{"id":"6080","index":24704,"sub_indices":[{"index":0,"desc":"Charger_state_of_charge","kind":0,"data_type":{"type":3,"attr":0,"lower":0,"upper":0},"access_type":{"type":2,"attr":0,"lower":0,"upper":0},"low_limit":{"value":0,"attr":0,"lower":0,"upper":0},"high_limit":{"value":0,"attr":0,"lower":0,"upper":0},"default_value":{"value":255,"attr":0,"lower":0,"upper":0},"mappable":{"value":true,"attr":0,"lower":0,"upper":0}}],"code":{"type":3,"attr":2,"lower":0,"upper":0},"min_elements":{"value":0,"attr":0,"lower":0,"upper":0},"max_elements":{"value":0,"attr":0,"lower":0,"upper":0},"desc":"Charger_state_of_charge","kind":0},{"id":"6081","index":24705,"sub_indices":[{"index":0,"desc":"Battery_state_of_charge","kind":0,"data_type":{"type":3,"attr":0,"lower":0,"upper":0},"access_type":{"type":4,"attr":0,"lower":0,"upper":0},"low_limit":{"value":0,"attr":0,"lower":0,"upper":0},"high_limit":{"value":0,"attr":0,"lower":0,"upper":0},"default_value":{"value":0,"attr":0,"lower":0,"upper":0},"mappable":{"value":true,"attr":0,"lower":0,"upper":0}}],"code":{"type":3,"attr":2,"lower":0,"upper":0},"min_elements":{"value":0,"attr":0,"lower":0,"upper":0},"max_elements":{"value":0,"attr":0,"lower":0,"upper":0},"desc":"Battery_state_of_charge","kind":0}]
